notifications:
  email:
    false

sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

install:
  - pip install -r requirements.txt

script:
  - python3 setup.py test
