notifications:
  email:
    false

sudo: false

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

install:
  - pip install -r requirements.txt

script:
  - pip install -r requirements-test.txt
  - nose2 --pretty-assert -v
